### ISSUE TITLE
Not working for 1.21.1

### ISSUE THREAD

**Issue by TheHanfried** [VatinMc/cursor-anchor#2]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Cursor anchor' (cursor-anchor) 1.1.0 with any version that is compatible with:
		 - minecraft 1.21.1
More details:
	 - Mod 'Cursor anchor' (cursor-anchor) 1.1.0 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I have checked. I downloaded the right version of the mod.

**Comment by VatinMc** [comment]
Ty for report. Most likely the mod.json is wrong. I will have a look at it tomorrow.

**Comment by TheHanfried** [comment]
Alright, thank you very much :) 
Never thought I needed a mod like this, but it seems really good and such a big QoL improvement.

**Comment by VatinMc** [comment]
Fixed now!
Feel free to post improvement suggestions! :)

**Comment by TheHanfried** [comment]
Thank you so much :) I will gladly test it to the fullest and if there is anything I can suggest, i will :)
when will the download usually be available on Modrinth or here? (Sorry im new to contacting the creators of mods :D)

**Comment by VatinMc** [comment]
You're welcome :)  
Thank you very much!  
Basically the same. It's a few minutes earlier on here. I would prefer if you use modrinth, because I can see the amount of downloads.

**Comment by TheHanfried** [comment]
Im so sorry to bother you :D When will the fixed version usually be uploaded ? Because its still not on modrinth or even here. ^^ Does it take a couple days because of authorisation stuff?

Thanks again for your help

**Comment by VatinMc** [comment]
No need to feel sorry, actually you are helping me!
I swapped the .jar-file, with new one, so if you download new jar it should be working.
If it doesn’t, please report here so I can have a look on what went wrong.

Also give feedback if it works, so I can close issue.

**Comment by TheHanfried** [comment]
I downloaded the 1.21.1 Version on Modrinth again and its still saying that its not for 1.21.1

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Cursor anchor' (cursor-anchor) 1.1.0 with any version that is compatible with:
		 - minecraft 1.21.1
More details:
	 - Mod 'Cursor anchor' (cursor-anchor) 1.1.0 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Still not all mods are out for 1.21.4, so I am still playing on 1.21.1

**Comment by VatinMc** [comment]
My bad. Again, thank you very much! :)
Now I released version for [1.21.1](https://github.com/VatinMc/cursor-anchor/releases/tag/1.21.1)
Modrinth also has own version for [1.21.1](https://modrinth.com/mod/cursor-anchor/version/MmikTVnj) now.
